import colors from "tailwindcss/colors";
import type { PaletteSemantic } from "./palette.types.ts";

export const PALETTE_SEMANTICS: PaletteSemantic = {
  red: {
    light: {
      contrast: colors.white,
      fg: colors.red["700"],
      subtle: colors.red["100"],
      muted: colors.red["200"],
      emphasized: colors.red["300"],
      solid: colors.red["600"],
      focusRing: colors.red["500"],
      border: colors.red["500"],
    },
    dark: {
      contrast: colors.white,
      fg: colors.red["300"],
      subtle: colors.red["950"],
      muted: colors.red["900"],
      emphasized: colors.red["700"],
      solid: colors.red["600"],
      focusRing: colors.red["500"],
      border: colors.red["400"],
    },
  },
  orange: {
    light: {
      contrast: colors.white,
      fg: colors.orange["700"],
      subtle: colors.orange["100"],
      muted: colors.orange["200"],
      emphasized: colors.orange["300"],
      solid: colors.orange["500"],
      focusRing: colors.orange["500"],
      border: colors.orange["500"],
    },
    dark: {
      contrast: colors.black,
      fg: colors.orange["300"],
      subtle: colors.orange["950"],
      muted: colors.orange["900"],
      emphasized: colors.orange["700"],
      solid: colors.orange["500"],
      focusRing: colors.orange["500"],
      border: colors.orange["400"],
    },
  },
  amber: {
    light: {
      contrast: colors.black,
      fg: colors.amber["700"],
      subtle: colors.amber["100"],
      muted: colors.amber["200"],
      emphasized: colors.amber["300"],
      solid: colors.amber["400"],
      focusRing: colors.amber["500"],
      border: colors.amber["500"],
    },
    dark: {
      contrast: colors.black,
      fg: colors.amber["300"],
      subtle: colors.amber["950"],
      muted: colors.amber["900"],
      emphasized: colors.amber["700"],
      solid: colors.amber["400"],
      focusRing: colors.amber["500"],
      border: colors.amber["400"],
    },
  },
  yellow: {
    light: {
      contrast: colors.black,
      fg: colors.yellow["700"],
      subtle: colors.yellow["100"],
      muted: colors.yellow["200"],
      emphasized: colors.yellow["300"],
      solid: colors.yellow["300"],
      focusRing: colors.yellow["500"],
      border: colors.yellow["500"],
    },
    dark: {
      contrast: colors.black,
      fg: colors.yellow["300"],
      subtle: colors.yellow["950"],
      muted: colors.yellow["900"],
      emphasized: colors.yellow["700"],
      solid: colors.yellow["300"],
      focusRing: colors.yellow["500"],
      border: colors.yellow["500"],
    },
  },
  lime: {
    light: {
      contrast: colors.black,
      fg: colors.lime["700"],
      subtle: colors.lime["100"],
      muted: colors.lime["200"],
      emphasized: colors.lime["300"],
      solid: colors.lime["500"],
      focusRing: colors.lime["500"],
      border: colors.lime["500"],
    },
    dark: {
      contrast: colors.black,
      fg: colors.lime["300"],
      subtle: colors.lime["950"],
      muted: colors.lime["900"],
      emphasized: colors.lime["700"],
      solid: colors.lime["500"],
      focusRing: colors.lime["500"],
      border: colors.lime["400"],
    },
  },
  green: {
    light: {
      contrast: colors.white,
      fg: colors.green["700"],
      subtle: colors.green["100"],
      muted: colors.green["200"],
      emphasized: colors.green["300"],
      solid: colors.green["600"],
      focusRing: colors.green["500"],
      border: colors.green["500"],
    },
    dark: {
      contrast: colors.white,
      fg: colors.green["300"],
      subtle: colors.green["950"],
      muted: colors.green["900"],
      emphasized: colors.green["700"],
      solid: colors.green["600"],
      focusRing: colors.green["500"],
      border: colors.green["400"],
    },
  },
  emerald: {
    light: {
      contrast: colors.white,
      fg: colors.emerald["700"],
      subtle: colors.emerald["100"],
      muted: colors.emerald["200"],
      emphasized: colors.emerald["300"],
      solid: colors.emerald["600"],
      focusRing: colors.emerald["500"],
      border: colors.emerald["500"],
    },
    dark: {
      contrast: colors.white,
      fg: colors.emerald["300"],
      subtle: colors.emerald["950"],
      muted: colors.emerald["900"],
      emphasized: colors.emerald["700"],
      solid: colors.emerald["600"],
      focusRing: colors.emerald["500"],
      border: colors.emerald["400"],
    },
  },
  teal: {
    light: {
      contrast: colors.white,
      fg: colors.teal["700"],
      subtle: colors.teal["100"],
      muted: colors.teal["200"],
      emphasized: colors.teal["300"],
      solid: colors.teal["600"],
      focusRing: colors.teal["500"],
      border: colors.teal["500"],
    },
    dark: {
      contrast: colors.white,
      fg: colors.teal["300"],
      subtle: colors.teal["950"],
      muted: colors.teal["900"],
      emphasized: colors.teal["700"],
      solid: colors.teal["600"],
      focusRing: colors.teal["500"],
      border: colors.teal["400"],
    },
  },
  cyan: {
    light: {
      contrast: colors.white,
      fg: colors.cyan["700"],
      subtle: colors.cyan["100"],
      muted: colors.cyan["200"],
      emphasized: colors.cyan["300"],
      solid: colors.cyan["600"],
      focusRing: colors.cyan["500"],
      border: colors.cyan["500"],
    },
    dark: {
      contrast: colors.white,
      fg: colors.cyan["300"],
      subtle: colors.cyan["950"],
      muted: colors.cyan["900"],
      emphasized: colors.cyan["700"],
      solid: colors.cyan["600"],
      focusRing: colors.cyan["500"],
      border: colors.cyan["400"],
    },
  },
  sky: {
    light: {
      contrast: colors.white,
      fg: colors.sky["700"],
      subtle: colors.sky["100"],
      muted: colors.sky["200"],
      emphasized: colors.sky["300"],
      solid: colors.sky["600"],
      focusRing: colors.sky["500"],
      border: colors.sky["500"],
    },
    dark: {
      contrast: colors.white,
      fg: colors.sky["300"],
      subtle: colors.sky["950"],
      muted: colors.sky["900"],
      emphasized: colors.sky["700"],
      solid: colors.sky["600"],
      focusRing: colors.sky["500"],
      border: colors.sky["400"],
    },
  },
  blue: {
    light: {
      contrast: colors.white,
      fg: colors.blue["700"],
      subtle: colors.blue["100"],
      muted: colors.blue["200"],
      emphasized: colors.blue["300"],
      solid: colors.blue["600"],
      focusRing: colors.blue["500"],
      border: colors.blue["500"],
    },
    dark: {
      contrast: colors.white,
      fg: colors.blue["300"],
      subtle: colors.blue["950"],
      muted: colors.blue["900"],
      emphasized: colors.blue["700"],
      solid: colors.blue["600"],
      focusRing: colors.blue["500"],
      border: colors.blue["400"],
    },
  },
  indigo: {
    light: {
      contrast: colors.white,
      fg: colors.indigo["700"],
      subtle: colors.indigo["100"],
      muted: colors.indigo["200"],
      emphasized: colors.indigo["300"],
      solid: colors.indigo["600"],
      focusRing: colors.indigo["500"],
      border: colors.indigo["500"],
    },
    dark: {
      contrast: colors.white,
      fg: colors.indigo["300"],
      subtle: colors.indigo["950"],
      muted: colors.indigo["900"],
      emphasized: colors.indigo["700"],
      solid: colors.indigo["600"],
      focusRing: colors.indigo["500"],
      border: colors.indigo["400"],
    },
  },
  violet: {
    light: {
      contrast: colors.white,
      fg: colors.violet["700"],
      subtle: colors.violet["100"],
      muted: colors.violet["200"],
      emphasized: colors.violet["300"],
      solid: colors.violet["600"],
      focusRing: colors.violet["500"],
      border: colors.violet["500"],
    },
    dark: {
      contrast: colors.white,
      fg: colors.violet["300"],
      subtle: colors.violet["950"],
      muted: colors.violet["900"],
      emphasized: colors.violet["700"],
      solid: colors.violet["600"],
      focusRing: colors.violet["500"],
      border: colors.violet["400"],
    },
  },
  purple: {
    light: {
      contrast: colors.white,
      fg: colors.purple["700"],
      subtle: colors.purple["100"],
      muted: colors.purple["200"],
      emphasized: colors.purple["300"],
      solid: colors.purple["600"],
      focusRing: colors.purple["500"],
      border: colors.purple["500"],
    },
    dark: {
      contrast: colors.white,
      fg: colors.purple["300"],
      subtle: colors.purple["950"],
      muted: colors.purple["900"],
      emphasized: colors.purple["700"],
      solid: colors.purple["600"],
      focusRing: colors.purple["500"],
      border: colors.purple["400"],
    },
  },
  fuchsia: {
    light: {
      contrast: colors.white,
      fg: colors.fuchsia["700"],
      subtle: colors.fuchsia["100"],
      muted: colors.fuchsia["200"],
      emphasized: colors.fuchsia["300"],
      solid: colors.fuchsia["600"],
      focusRing: colors.fuchsia["500"],
      border: colors.fuchsia["500"],
    },
    dark: {
      contrast: colors.white,
      fg: colors.fuchsia["300"],
      subtle: colors.fuchsia["950"],
      muted: colors.fuchsia["900"],
      emphasized: colors.fuchsia["700"],
      solid: colors.fuchsia["600"],
      focusRing: colors.fuchsia["500"],
      border: colors.fuchsia["400"],
    },
  },
  pink: {
    light: {
      contrast: colors.white,
      fg: colors.pink["700"],
      subtle: colors.pink["100"],
      muted: colors.pink["200"],
      emphasized: colors.pink["300"],
      solid: colors.pink["600"],
      focusRing: colors.pink["500"],
      border: colors.pink["500"],
    },
    dark: {
      contrast: colors.white,
      fg: colors.pink["300"],
      subtle: colors.pink["950"],
      muted: colors.pink["900"],
      emphasized: colors.pink["700"],
      solid: colors.pink["600"],
      focusRing: colors.pink["500"],
      border: colors.pink["400"],
    },
  },
  rose: {
    light: {
      contrast: colors.white,
      fg: colors.rose["700"],
      subtle: colors.rose["100"],
      muted: colors.rose["200"],
      emphasized: colors.rose["300"],
      solid: colors.rose["600"],
      focusRing: colors.rose["500"],
      border: colors.rose["500"],
    },
    dark: {
      contrast: colors.white,
      fg: colors.rose["300"],
      subtle: colors.rose["950"],
      muted: colors.rose["900"],
      emphasized: colors.rose["700"],
      solid: colors.rose["600"],
      focusRing: colors.rose["500"],
      border: colors.rose["400"],
    },
  },
  slate: {
    light: {
      contrast: colors.white,
      fg: colors.slate["700"],
      subtle: colors.slate["100"],
      muted: colors.slate["200"],
      emphasized: colors.slate["300"],
      solid: colors.slate["700"],
      focusRing: colors.slate["400"],
      border: colors.slate["500"],
    },
    dark: {
      contrast: colors.black,
      fg: colors.slate["300"],
      subtle: colors.slate["800"],
      muted: colors.slate["700"],
      emphasized: colors.slate["700"],
      solid: colors.slate["200"],
      focusRing: colors.slate["400"],
      border: colors.slate["400"],
    },
  },
  gray: {
    light: {
      contrast: colors.white,
      fg: colors.gray["700"],
      subtle: colors.gray["100"],
      muted: colors.gray["200"],
      emphasized: colors.gray["300"],
      solid: colors.gray["700"],
      focusRing: colors.gray["400"],
      border: colors.gray["500"],
    },
    dark: {
      contrast: colors.black,
      fg: colors.gray["300"],
      subtle: colors.gray["800"],
      muted: colors.gray["700"],
      emphasized: colors.gray["700"],
      solid: colors.gray["200"],
      focusRing: colors.gray["400"],
      border: colors.gray["400"],
    },
  },
  zinc: {
    light: {
      contrast: colors.white,
      fg: colors.zinc["700"],
      subtle: colors.zinc["100"],
      muted: colors.zinc["200"],
      emphasized: colors.zinc["300"],
      solid: colors.zinc["700"],
      focusRing: colors.zinc["400"],
      border: colors.zinc["500"],
    },
    dark: {
      contrast: colors.black,
      fg: colors.zinc["300"],
      subtle: colors.zinc["800"],
      muted: colors.zinc["700"],
      emphasized: colors.zinc["700"],
      solid: colors.zinc["200"],
      focusRing: colors.zinc["400"],
      border: colors.zinc["400"],
    },
  },
  neutral: {
    light: {
      contrast: colors.white,
      fg: colors.neutral["700"],
      subtle: colors.neutral["100"],
      muted: colors.neutral["200"],
      emphasized: colors.neutral["300"],
      solid: colors.neutral["700"],
      focusRing: colors.neutral["400"],
      border: colors.neutral["500"],
    },
    dark: {
      contrast: colors.black,
      fg: colors.neutral["300"],
      subtle: colors.neutral["800"],
      muted: colors.neutral["700"],
      emphasized: colors.neutral["700"],
      solid: colors.neutral["200"],
      focusRing: colors.neutral["400"],
      border: colors.neutral["400"],
    },
  },
  stone: {
    light: {
      contrast: colors.white,
      fg: colors.stone["700"],
      subtle: colors.stone["100"],
      muted: colors.stone["200"],
      emphasized: colors.stone["300"],
      solid: colors.stone["700"],
      focusRing: colors.stone["400"],
      border: colors.stone["500"],
    },
    dark: {
      contrast: colors.black,
      fg: colors.stone["300"],
      subtle: colors.stone["800"],
      muted: colors.stone["700"],
      emphasized: colors.stone["700"],
      solid: colors.stone["200"],
      focusRing: colors.stone["400"],
      border: colors.stone["400"],
    },
  },
};
